version: 0.2


phases:
  install:
    runtime-versions:
      php: 8.2

  pre_build:
    commands:
      - export KUBECONFIG=$HOME/.kube/config
   
      
  build:
    commands:
      - echo "Setting Environment Variables related to AWS CLI for Kube Config Setup"
      - CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::678554781153:role/service-role/Vaccination-CodeBuildServiceRole --role-session-name eks-codebuild --region ap-southeast-1)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - echo "Update Kube Config"
      - aws eks update-kubeconfig --name vaccination-system-eks --region ap-southeast-1
      
  post_build:
    commands:
      - echo "Apply changes to kube manifests"  
      - kubectl get pods -A

      - kubectl apply -f k8s-manifests/registration-configmap.yaml -n vaccination-system-dev
      - kubectl apply -f k8s-manifests/auth-secret.yaml
      - kubectl apply -f k8s-manifests/auth-dev.yaml

privilegedMode: true
